# Service Configuration

api:
  host: "0.0.0.0"
  port: 8000
  max_workers: 4
  timeout: 300
  cors_enabled: true
  
authentication:
  api_key_required: true
  rate_limiting:
    requests_per_minute: 60
    requests_per_hour: 1000
    
logging:
  level: "INFO"
  format: "json"
  file: "logs/qwen_vl_service.log"
  rotation: "1 day"
  retention: "30 days"

monitoring:
  metrics_enabled: true
  health_check_endpoint: "/health"
  metrics_endpoint: "/metrics"
  
  prometheus:
    enabled: true
    port: 9090
    
  grafana:
    enabled: true
    port: 3000

# Performance settings
performance:
  gpu_memory_fraction: 0.95
  mixed_precision: true
  gradient_checkpointing: true
  compile_model: true
  
cache:
  enabled: true
  type: "redis"
  host: "localhost"
  port: 6379
  ttl: 3600
